export const data = [
    {
        size_id: "1",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RN",
        size: "80",
    },
    {
        size_id: "2",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RN",
        size: "85",
    },
    {
        size_id: "3",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RN",
        size: "90",
    },
    {
        size_id: "4",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RN",
        size: "95",
    },
    {
        size_id: "5",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RN",
        size: "100",
    },
    {
        size_id: "6",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RN",
        size: "105",
    },
    {
        size_id: "7",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RNS",
        size: "80",
    },
    {
        size_id: "8",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RNS",
        size: "85",
    },
    {
        size_id: "9",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RNS",
        size: "90",
    },
    {
        size_id: "10",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RNS",
        size: "95",
    },
    {
        size_id: "11",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RNS",
        size: "100",
    },
    {
        size_id: "12",
        id: "1",
        name: "COOLD VEST WHITE",
        style: "RNS",
        size: "105",
    },
    {
        size_id: "13",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RN",
        size: "80",
    },
    {
        size_id: "14",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RN",
        size: "85",
    },
    {
        size_id: "15",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RN",
        size: "90",
    },
    {
        size_id: "16",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RN",
        size: "95",
    },
    {
        size_id: "17",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RN",
        size: "100",
    },
    {
        size_id: "18",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RN",
        size: "105",
    },
    {
        size_id: "19",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RNS",
        size: "80",
    },
    {
        size_id: "20",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RNS",
        size: "85",
    },
    {
        size_id: "21",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RNS",
        size: "90",
    },
    {
        size_id: "22",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RNS",
        size: "95",
    },
    {
        size_id: "23",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RNS",
        size: "100",
    },
    {
        size_id: "24",
        id: "2",
        name: "COOLD VEST COLOR",
        style: "RNS",
        size: "105",
    },
    {
        size_id: "25",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RN",
        size: "80",
    },
    {
        size_id: "26",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RN",
        size: "85",
    },
    {
        size_id: "27",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RN",
        size: "90",
    },
    {
        size_id: "28",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RN",
        size: "95",
    },
    {
        size_id: "29",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RN",
        size: "100",
    },
    {
        size_id: "30",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RN",
        size: "105",
    },
    {
        size_id: "31",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RNS",
        size: "80",
    },
    {
        size_id: "32",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RNS",
        size: "85",
    },
    {
        size_id: "33",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RNS",
        size: "90",
    },
    {
        size_id: "34",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RNS",
        size: "95",
    },
    {
        size_id: "35",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RNS",
        size: "100",
    },
    {
        size_id: "36",
        id: "3",
        name: "COOLD VEST WHITE PKT",
        style: "RNS",
        size: "105",
    },
    {
        size_id: "153",
        id: "17",
        name: "TREND PLAIN TRUNK",
        style: "IE",
        size: "80",
    },
    {
        size_id: "154",
        id: "17",
        name: "TREND PLAIN TRUNK",
        style: "IE",
        size: "85",
    },
    {
        size_id: "155",
        id: "17",
        name: "TREND PLAIN TRUNK",
        style: "IE",
        size: "90",
    },
    {
        size_id: "156",
        id: "17",
        name: "TREND PLAIN TRUNK",
        style: "IE",
        size: "95",
    },
    {
        size_id: "157",
        id: "17",
        name: "TREND PLAIN TRUNK",
        style: "IE",
        size: "100",
    },
    {
        size_id: "158",
        id: "17",
        name: "TREND PLAIN TRUNK",
        style: "IE",
        size: "105",
    },
    {
        size_id: "159",
        id: "18",
        name: "TREND SMART",
        style: "IE",
        size: "80",
    },
    {
        size_id: "160",
        id: "18",
        name: "TREND SMART",
        style: "IE",
        size: "85",
    },
    {
        size_id: "161",
        id: "18",
        name: "TREND SMART",
        style: "IE",
        size: "90",
    },
    {
        size_id: "162",
        id: "18",
        name: "TREND SMART",
        style: "IE",
        size: "95",
    },
    {
        size_id: "163",
        id: "18",
        name: "TREND SMART",
        style: "IE",
        size: "100",
    },
    {
        size_id: "164",
        id: "18",
        name: "TREND SMART",
        style: "IE",
        size: "105",
    },
    {
        size_id: "165",
        id: "19",
        name: "TREND TRUNK LINER",
        style: "IE",
        size: "80",
    },
    {
        size_id: "166",
        id: "19",
        name: "TREND TRUNK LINER",
        style: "IE",
        size: "85",
    },
    {
        size_id: "167",
        id: "19",
        name: "TREND TRUNK LINER",
        style: "IE",
        size: "90",
    },
    {
        size_id: "168",
        id: "19",
        name: "TREND TRUNK LINER",
        style: "IE",
        size: "95",
    },
    {
        size_id: "169",
        id: "19",
        name: "TREND TRUNK LINER",
        style: "IE",
        size: "100",
    },
    {
        size_id: "170",
        id: "19",
        name: "TREND TRUNK LINER",
        style: "IE",
        size: "105",
    },
    {
        size_id: "171",
        id: "20",
        name: "TREND TRUNK PKT",
        style: "IE",
        size: "80",
    },
    {
        size_id: "172",
        id: "20",
        name: "TREND TRUNK PKT",
        style: "IE",
        size: "85",
    },
    {
        size_id: "173",
        id: "20",
        name: "TREND TRUNK PKT",
        style: "IE",
        size: "90",
    },
    {
        size_id: "174",
        id: "20",
        name: "TREND TRUNK PKT",
        style: "IE",
        size: "95",
    },
    {
        size_id: "175",
        id: "20",
        name: "TREND TRUNK PKT",
        style: "IE",
        size: "100",
    },
    {
        size_id: "176",
        id: "20",
        name: "TREND TRUNK PKT",
        style: "IE",
        size: "105",
    },
    {
        size_id: "177",
        id: "21",
        name: "CLASSIC TRUNK",
        style: "IE",
        size: "80",
    },
    {
        size_id: "178",
        id: "21",
        name: "CLASSIC TRUNK",
        style: "IE",
        size: "85",
    },
    {
        size_id: "179",
        id: "21",
        name: "CLASSIC TRUNK",
        style: "IE",
        size: "90",
    },
    {
        size_id: "180",
        id: "21",
        name: "CLASSIC TRUNK",
        style: "IE",
        size: "95",
    },
    {
        size_id: "181",
        id: "21",
        name: "CLASSIC TRUNK",
        style: "IE",
        size: "100",
    },
    {
        size_id: "182",
        id: "21",
        name: "CLASSIC TRUNK",
        style: "IE",
        size: "105",
    },
    {
        size_id: "183",
        id: "22",
        name: "CLASSIC TRUNK FCD",
        style: "IE",
        size: "80",
    },
    {
        size_id: "184",
        id: "22",
        name: "CLASSIC TRUNK FCD",
        style: "IE",
        size: "85",
    },
    {
        size_id: "185",
        id: "22",
        name: "CLASSIC TRUNK FCD",
        style: "IE",
        size: "90",
    },
    {
        size_id: "186",
        id: "22",
        name: "CLASSIC TRUNK FCD",
        style: "IE",
        size: "95",
    },
    {
        size_id: "187",
        id: "22",
        name: "CLASSIC TRUNK FCD",
        style: "IE",
        size: "100",
    },
    {
        size_id: "188",
        id: "22",
        name: "CLASSIC TRUNK FCD",
        style: "IE",
        size: "105",
    },
    {
        size_id: "261",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "IE",
        size: "75",
    },
    {
        size_id: "262",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "IE",
        size: "80",
    },
    {
        size_id: "263",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "IE",
        size: "85",
    },
    {
        size_id: "264",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "IE",
        size: "90",
    },
    {
        size_id: "265",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "IE",
        size: "95",
    },
    {
        size_id: "266",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "IE",
        size: "100",
    },
    {
        size_id: "267",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "IE",
        size: "105",
    },
    {
        size_id: "268",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "OE",
        size: "75",
    },
    {
        size_id: "269",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "OE",
        size: "80",
    },
    {
        size_id: "270",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "OE",
        size: "85",
    },
    {
        size_id: "271",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "OE",
        size: "90",
    },
    {
        size_id: "272",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "OE",
        size: "95",
    },
    {
        size_id: "273",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "OE",
        size: "100",
    },
    {
        size_id: "274",
        id: "35",
        name: "CLASSIC BRIEF",
        style: "OE",
        size: "105",
    },
    {
        size_id: "275",
        id: "36",
        name: "CLASSIC PLUS",
        style: "IE",
        size: "80",
    },
    {
        size_id: "276",
        id: "36",
        name: "CLASSIC PLUS",
        style: "IE",
        size: "85",
    },
    {
        size_id: "277",
        id: "36",
        name: "CLASSIC PLUS",
        style: "IE",
        size: "90",
    },
    {
        size_id: "278",
        id: "36",
        name: "CLASSIC PLUS",
        style: "IE",
        size: "95",
    },
    {
        size_id: "279",
        id: "36",
        name: "CLASSIC PLUS",
        style: "IE",
        size: "100",
    },
    {
        size_id: "280",
        id: "36",
        name: "CLASSIC PLUS",
        style: "IE",
        size: "105",
    },
];
